//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vector
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    

    public class MyInitializer : DropCreateDatabaseAlways<MyShopContext>
    {
        protected override void Seed(MyShopContext context)
        {
           
            List<Supplier> supps = new List<Supplier>
            {
                new Supplier{SupplierID=1,SupplierName="Exotic Liquid",City="London",Country="UK" },
                new Supplier{SupplierID=2,SupplierName="New Orleans Cajun Delights",City="New Orleans",Country="USA" },
                new Supplier{SupplierID=3,SupplierName="Grandma Kelly’s Homestead",City="Ann Arbor",Country="USA" },
                new Supplier{SupplierID=4,SupplierName="Tokyo Traders",City="Tokyo",Country="Japan" },
                new Supplier{SupplierID=5,SupplierName="Cooperativa de Quesos ‘Las Cabras’",City="Oviedo",Country="Spain" }
            };
            foreach (var item in supps)
            {
                context.Suppliers.Add(item);
            }
            List<Category> cats = new List<Category>
            {
                new Category{CategoryID =1, CategoryName="Beverages",CDescription="Soft drinks, coffees, teas, beers, and ales" },
                new Category{CategoryID =2, CategoryName="Condiments",CDescription="Sweet and savory sauces, relishes, spreads, and seasonings" },
                new Category{CategoryID =3, CategoryName="Confections",CDescription="Desserts, candies, and sweet breads" },
                new Category{CategoryID =4, CategoryName="Dairy Products",CDescription="Cheeses" },
                new Category{CategoryID =5, CategoryName="Grains/Cereals",CDescription="Breads, crackers, pasta, and cereal" },


            };
            foreach (var item in cats)
            {
                context.Categories.Add(item);
            }
            List<Product> prods = new List<Product>
            {
                new Product{ProductID=1,ProductName="Chais" ,CategoryID=1, SupplierID= 1,Price=18 },
                new Product{ProductID=2,ProductName="Chang" ,CategoryID=1, SupplierID= 1,Price=19 },
                new Product{ProductID=3,ProductName="Aniseed Syrup" ,CategoryID=1, SupplierID= 2,Price=10 },
                new Product{ProductID=4,ProductName="Chef Anton’s Cajun Seasoning" ,CategoryID=2, SupplierID= 2,Price=22 },
                new Product{ProductID=5,ProductName=";Chef Anton’s Gumbo Mix" ,CategoryID=2, SupplierID= 2,Price=(decimal?)21.35 },

            };
            foreach (var item in prods)
            {
                context.Products.Add(item);
            }



            context.SaveChanges();
        }
    }

    public partial class MyShopContext : DbContext
    {
        static MyShopContext()
        {
            Database.SetInitializer<MyShopContext>(new MyInitializer());
        }
        public MyShopContext()
            : base("name=MyShopContext")
        { }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
    }
}
